### ISSUE TITLE
Demo Examples does not work

### ISSUE THREAD

**Issue by prasadk1884** [GoogleCloudPlatform/cloud-composer#104]
Hi Team,
I have tried to check through this utility by running the Demo examples provided but it does not generate the output.  Following are few observations : 
1)  Demo example manual says to provide the properties file parameter i.e. -p, But this parameter does not exist in code and not acceptable while running the o2a.py  script. It ran without providing the -p parameter.

2) The instruction manual say's we have to run demo example with below command, but it actually gives error -
Command : python o2a.py -i examples/demo/workflow.xml -p examples/demo/job.properties
Error : NotADirectoryError: [Errno 20] Not a directory: 'examples/demo/workflow.xml/workflow.xml'
I had to run it by giving input till directory level only(without adding workflow.xml to input parameter) and then it went ahead of this error. 

3) Now I am getting a further error as : KeyError: 'dataproc_cluster'. and no output is getting generated as of yet. 

Can someone help if there is any stable version available? We are working on a project where this utility will be useful and looking forward to use it.

**Comment by sprzedwojski** [comment]
Hi @prasadk1884!
Thanks for the interest in our project. It's in a very early stage right now and we are working on it very intensely.
That said the docs have fallen behind a bit and do not reflect the current status of the tool. **This is a top priority for us and the docs will be up to date very soon.**

In order for the `demo` to work you need to copy the `examples/demo/configuration.template.properties` file, rename it to `configuration.properties` and fill in the missing data.
This can be done automatically using our system testing tool `run-sys-test` or manually.

The command to run the example is now:
```python o2a.py -i examples/demo -o output/demo```

As you can see it's a little different from the docs (like I said, they will be updated shortly), however if you run
```
python o2a.py -h
```
you'll see all the available arguments.

I hope now it'll work for you. Feel free to ask any question :)

**Comment by marutmisra08** [comment]
After following the steps provided i am able to run demo example. 
But when i tried loading converted demo.py in airflow, i am getting error. (The dag is broken)
Also in Converted dag i am seeing import statement (import o2a_libs) , which are not required in production environment, are those necessary to put in converted dag

Please suggest

**Comment by potiuk** [comment]
Thanks for your comment! You can take a look at `run-sys-test` script - it can actually help you to run the code in an automated way. 

What do you mean by Dag broken ? The demo.py it should not be broken. We test whether it compiles after we run conversion in TravisCI so it should parse well (providing that you have the import). But we are still working on it very actively so it might be that it does not fully run e2e yet.

There are some prerequisites that have to be met if you want to run the code - including copying the reusable libraries (these steps are executed automatically if you run `run-sys-test` script - specifically `prepare_composer` function does it:

```python
function prepare_composer {
    header "Prepares Composer by copying reusable library files"
    gsutil cp "${LOCAL_SCRIPTS_DIR}/*" "gs://${COMPOSER_DAG_BUCKET}/data/"
    gsutil cp "${LOCAL_O2A_LIBS_DIR}/*" "gs://${COMPOSER_DAG_BUCKET}/dags/o2a_libs/"
    footer
}
```

**Comment by potiuk** [comment]
The current demo examples should work now out-of-the-box if you follow the README doc
