### ISSUE TITLE
Missing tests for MapReduce 

### ISSUE THREAD

**Issue by mik-laj** [GoogleCloudPlatform/cloud-composer#114]
Hello,

MapReduce has a small coverage in tests.  Please add the missing tests.

Reference: 
https://github.com/GoogleCloudPlatform/cloud-composer/commit/147ca1cb6f38101d6d2968a645cf1cb38ca193b6#r33302664
https://github.com/GoogleCloudPlatform/cloud-composer/commit/147ca1cb6f38101d6d2968a645cf1cb38ca193b6#r33302768
https://github.com/GoogleCloudPlatform/cloud-composer/commit/147ca1cb6f38101d6d2968a645cf1cb38ca193b6#r33302746

Best,
Kamil

**Comment by sprzedwojski** [comment]
Done in #150
