### ISSUE TITLE
Trigger rule values

### ISSUE THREAD

**Issue by sprzedwojski** [GoogleCloudPlatform/cloud-composer#119]
Right now the mappers' constructor accepts a TriggerRule value, which is then completely ignored.
Instead there's an `update_trigger_rules()` method in `parser`, which sets them according to whether the particular task is a `fail` task (`ONE_FAILED`), any other task (`ONE_SUCCESS`, although it should rather be `ALL_SUCCESS`) or when it can't be determined which type a task is, it's set to `DUMMY`.

One approach would be to completely remove the constructor setting of the trigger rules and rely comletely on the `update_trigger_rules()` method.

However other ideas are welcome.

**Comment by mik-laj** [comment]
Currently, mapper is not responsible for updating trigger rules. ParsedNode is responsible for that, but mapper requires triggering rules, because they are part of the task object that mapper creates. Each mapper has trigger rules in the constructor to be able to set the default value.
