### ISSUE TITLE
Capture-Output and wf:actionData implementation question

### ISSUE THREAD

**Issue by prasadk1884** [GoogleCloudPlatform/cloud-composer#153]
Hello,
Can you please let me know if this project support the tags and functions like `<capture-output/>` and `${wf:actionData('sshInit')['Status'] eq "PASS"}` from oozie and convert them to Composer Dag?

I got many oozie workflows using this and need to convert them to cloud composer.

**Comment by potiuk** [comment]
Wa are working on adding support for wf:<functions> very soon. First one (wf:conf) coming in #135 . Also Capture-output is something we want to add. I've added two issues #155 and #156 and #157 to make it clear.

When exactly I do not know yet. We are going to do some more detailed planning and set some milestones soon, so please subscribe to the project and see when those will be added and when we announce it. 

Maybe you will be one of the users that can test it (or you could even become contributor if you would like to add some of those features if you think that's a good idea. We are happy to involve more people from community to add missing features.

I close it now as we have those three new issues added. Feel free to subscribe to those issues to get notified about the progress.
