### ISSUE TITLE
Print full command to run command on Dataproc

### ISSUE THREAD

**Issue by mik-laj** [GoogleCloudPlatform/cloud-composer#168]
Hello

It would be nice if the run-sys-test would show a real command that will allow you to check the status of the oozie job, not just a description of how a programmer can do such a task
The description of how to do the task is interesting, but when performing the operation many times this task becomes boring. The ready command will improve our work.

Current output:
```
You can run the following commands on dataproc cluster to see the job status

oozie job -info <JOB_ID>
oozie job -log  <JOB_ID>
```
Expected output:
```
You can run the following commands to see the job status

run-sys-test -S -- oozie job -info '0000106-190423121107245-oozie-oozi-W'
run-sys-test -S -- oozie job -log '0000106-190423121107245-oozie-oozi-W'
```

**Comment by mik-laj** [comment]
@potiuk @sprzedwojski Can I put this task in the backlog? This is small and I will take only a little time.

**Comment by potiuk** [comment]
Sure. it's not super-trivial though until we get the output of the command via gcloud command which might be a bit tricky. I agree it would be super-helpful and I thought that we need that indeed. I think when I run the system tests for property change I might get frustrated enough to implement it :)
