### ISSUE TITLE
What to do if a task fails which is in the middle of a chain o tasks?

### ISSUE THREAD

**Issue by sprzedwojski** [GoogleCloudPlatform/cloud-composer#78]
Example DAG:
https://user-images.githubusercontent.com/12058428/56119017-80e2d700-5f6b-11e9-9360-71b282805fb8.png

Talk through with @mik-laj

**Comment by mik-laj** [comment]
In the example, this question might be: How to execute an error node when there will be an error in `chmod_fs_3_mkdir`? Currently, error node is trigger only for `chmod_fs_7_mod`. 
Problem is related to [trigger rule](https://airflow.readthedocs.io/en/latest/concepts.html#trigger-rules) and missing relations between error node and task in sequence of tasks.
